### PR TITLE
feat: update liquibase version for newest command console

### PR DESCRIPTION
**Pull request by WilliamHinschink**
Update liquibase version
Compatibility with newest database version (e.g.: Cassandra CQL)
Remove deprecated liquibase.resource.FileSystemResourceAccessor class

### CODE REVIEW

**Comment by MalloD12** [comment]
@stevesaliman

**Comment by WilliamHinschink** [comment]
> @stevesaliman

:heart:

**Comment by MalloD12** [comment]
Hey @stevesaliman, are you good moving forward with this PR? This one was updating Liquibase version to 4.27, not sure if now we almost have `4.29.1` we still want to update it to `4.27.0`, or if we want to update it to a newer version. 

Thanks,
Daniel.

**Comment by stevesaliman** [comment]
I think most of what is in this PR is part of the 4.0 release that I'm trying to get done.  It essentially drops support for Liquibase < 4.24, and works for newer versions.  I've been waiting on https://github.com/liquibase/liquibase/issues/5654 to be fixed, but I may have to release without it, even though it causes test failures in the Groovy DSL.

**Comment by MalloD12** [comment]
Let's see if Jason has some availability to fixing [#5654](https://github.com/liquibase/liquibase/issues/5654), if he doesn't then we can prioritize it with our internal team to fix it.

**Comment by stevesaliman** [comment]
The changes from this PR have been incorporated into the new 4.0.0 release.

**Pull request closed without merging**
